# Generated by Django 6.0.4 on 2026-04-27 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_books_genre_books_is_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='year',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
